// ui/app/pages/verif/otp.vue
<script setup lang="ts">
import { useForm } from '@tanstack/vue-form';
import { Mail } from 'lucide-vue-next';
import { REGEXP_ONLY_DIGITS } from 'vue-input-otp';
import { toast } from 'vue-sonner';
import { Badge } from '~/components/ui/badge';
import { Button } from '~/components/ui/button';
import { Card, CardAction, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '~/components/ui/card';
import { Field, FieldError, FieldGroup } from '~/components/ui/field';
import { errorHelper } from '~/lib/error-helper';
import type { User } from '~/utils/model/user';
import { verifOtp } from '~/utils/validation/auth';

definePageMeta({
    layout: "verif",
    middleware: ["check-session", "signup"]
})

const config = useRuntimeConfig();

const userData: User | undefined = inject("userData");
// const refreshUserData = inject("refreshUserData")

const COOLDOWN_KEY = 'otp_resend_expires_at'
const resendCooldown = ref(0)
const isResending = ref(false)

// Restore countdown dari localStorage saat mount, atau set default 60s jika pertama kali
onMounted(() => {
    const expiresAt = localStorage.getItem(COOLDOWN_KEY)
    if (expiresAt) {
        const remaining = Math.max(0, Math.floor((parseInt(expiresAt) - Date.now()) / 1000))
        if (remaining > 0) {
            resendCooldown.value = remaining
            startCountdown()
        } else {
            localStorage.removeItem(COOLDOWN_KEY)
        }
    } else {
        // Pertama kali masuk halaman = user baru dapat email, set countdown 60s
        resendCooldown.value = 60
        const expiresAt = Date.now() + (60 * 1000)
        localStorage.setItem(COOLDOWN_KEY, expiresAt.toString())
        startCountdown()
    }
})

function startCountdown() {
    const interval = setInterval(() => {
        resendCooldown.value--
        if (resendCooldown.value <= 0) {
            clearInterval(interval)
            localStorage.removeItem(COOLDOWN_KEY)
        }
    }, 1000)
}

async function resendOtp() {
    if (resendCooldown.value > 0 || isResending.value) return

    isResending.value = true
    try {
        await $fetch(`${config.public.apiBaseUrl}/session/otp/resend`, { method: 'PATCH', credentials: 'include' })

        // Set countdown 60 detik & simpan timestamp expired
        resendCooldown.value = 60
        const expiresAt = Date.now() + (60 * 1000)
        localStorage.setItem(COOLDOWN_KEY, expiresAt.toString())

        startCountdown()
    } catch (error) {
        console.error('Failed to resend OTP:', error)
    } finally {
        isResending.value = false
        toast.success('OTP has been resent to your email!')
    }
}

const form = useForm({
    defaultValues: {
        otp_code: "",
    },
    validators: {
        onSubmit: verifOtp
    },
    onSubmit: async ({ value }) => {
        try {
            await $fetch(`${config.public.apiBaseUrl}/auth/verif/otp`, {
                method: "PATCH",
                headers: {
                    "Content-Type": "application/json"
                },
                body: value,
                credentials: "include",
            })
        } catch (error) {
            await errorHelper(error)
        } finally {
            toast.success('OTP verified successfully! Please create your master password.')
            await navigateTo('/verif/password')
        }
    },
})



// eslint-disable-next-line @typescript-eslint/no-explicit-any
function isInvalid(field: any) {
    return field.state.meta.isTouched && !field.state.meta.isValid
}
</script>


<template>
    <div class="fixed top-1/2 left-1/2 -translate-y-1/2 -translate-x-1/2 w-xl shadow-2xl">
        <Card class="w-full max-w-xl shadow-lg">
            <CardHeader>
                <CardTitle class="text-2xl">Verify OTP</CardTitle>
                <CardDescription>
                    Hello <b class="text-primary">{{ userData?.username }}</b>, please enter
                    the OTP sent to your email, and please don't leave this page until
                    you have verified your account.
                </CardDescription>
                <CardAction>
                    <ClientOnly>
                        <Button
variant="link" type="button" :disabled="resendCooldown > 0 || isResending"
                            @click="resendOtp">
                            <span v-if="isResending">Sending...</span>
                            <span v-else-if="resendCooldown > 0">Resend in {{ resendCooldown }}s</span>
                            <span v-else>Resend OTP</span>
                        </Button>
                        <template #fallback>
                            <Button variant="link" type="button" disabled>
                                Loading...
                            </Button>
                        </template>
                    </ClientOnly>
                </CardAction>
            </CardHeader>

            <form class="space-y-6" @submit.prevent="form.handleSubmit">
                <CardContent class="flex justify-center flex-col items-center gap-4">
                    <Badge class="px-2 py-1">
                        <Mail /> {{ userData?.email }}
                    </Badge>
                    <div class="w-full max-w-1/2">
                        <FieldGroup>
                            <form.Field name="otp_code">
                                <template #default="{ field }">

                                    <Field :data-invalid="isInvalid(field)">
                                        <InputOTP
:model-value="field.state.value" :maxlength="6"
                                            :pattern="REGEXP_ONLY_DIGITS" @update:model-value="field.handleChange">
                                            <InputOTPGroup>
                                                <InputOTPSlot :index="0" />
                                                <InputOTPSlot :index="1" />
                                                <InputOTPSlot :index="2" />
                                            </InputOTPGroup>
                                            <InputOTPSeparator />
                                            <InputOTPGroup>
                                                <InputOTPSlot :index="3" />
                                                <InputOTPSlot :index="4" />
                                                <InputOTPSlot :index="5" />
                                            </InputOTPGroup>
                                        </InputOTP>
                                        <FieldError v-if="isInvalid(field)" :errors="field.state.meta.errors" />
                                    </Field>
                                </template>
                            </form.Field>
                        </FieldGroup>
                    </div>
                </CardContent>

                <CardFooter class="flex flex-col justify-start items-start">
                    <!-- <ClientOnly
              fallback={
                <span class="text-gray-400">
                  Loading expiration status...
                </span>
              }
            >
              <ExpirationStatus expiresAt={data?.data?.otpExpiresAt} />
            </ClientOnly> -->

                    <span class="text-sm text-muted-foreground">
                        Please enter the OTP code sent to your email.
                    </span>

                    <Button type="submit" class="cursor-pointer">
                        Submit
                        <!-- {isPendingOtpVerif ? (
                <>
                  <span class="animate-spin mr-2">⏳</span>
                  Verifying...
                </>
              ) : (
                'Submit'
              )} -->
                    </Button>
                </CardFooter>
            </form>
        </Card>
    </div>

</template>

// ui/src/routes/verification/otp/index.tsx
import {
  ClientOnly,
  createFileRoute,
  useNavigate,
} from '@tanstack/react-router'
import { Mail } from 'lucide-react'
import { toast } from 'sonner'
import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type { otpExpiresAt } from '@/model/user'
import type z from 'zod'
import { verifOtp } from '@/validation/auth'
import { Button } from '@/components/ui/button'
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { signUpMiddleware } from '@/middleware/signup'
import { fetchAPI } from '@/lib/custom-fetch'
import useCountDown from '@/hooks/use-countdown'
import { useAppForm } from '@/components/ui/custom-form'
import { FieldGroup } from '@/components/ui/field'

export const Route = createFileRoute('/verification/otp/')({
  server: {
    middleware: [signUpMiddleware],
  },
  component: RouteComponent,
  loader: ({ serverContext }) => {
    return { user: serverContext?.user.data }
  },
})

function ExpirationStatus({ expiresAt }: { expiresAt: string | undefined }) {
  const [isExpired, setIsExpired] = useState(false)

  useEffect(() => {
    if (!expiresAt) return

    const checkExpiration = () => {
      const now = new Date()
      const expiry = new Date(expiresAt)
      setIsExpired(expiry.getTime() - now.getTime() < 0)
    }

    checkExpiration()
    const interval = setInterval(checkExpiration, 1000)
    return () => clearInterval(interval)
  }, [expiresAt])

  if (isExpired) {
    return (
      <span className="text-red-500">
        OTP expired, please request a new one
      </span>
    )
  }

  return (
    <span className="text-emerald-500">Your OTP expires in 10 minutes</span>
  )
}

function RouteComponent() {
  const { user } = Route.useLoaderData()
  const queryClient = useQueryClient()
  const navigate = useNavigate()

  const { data } = useQuery({
    queryKey: ['otp-record'],
    queryFn: async () => {
      const res = await fetchAPI<otpExpiresAt>(
        `${import.meta.env.VITE_API_BASE_URL}/session/otp/expire`,
        {
          method: 'GET',
          credentials: 'include',
        },
      )
      return res
    },
    staleTime: 1000 * 60 * 5,
  })

  const { countdown, start } = useCountDown()

  const { mutate: resendOtp, isPending: isResending } = useMutation({
    mutationFn: async () => {
      const res = await fetchAPI(
        `${import.meta.env.VITE_API_BASE_URL}/session/otp/resend`,
        {
          credentials: 'include',
          method: 'PATCH',
        },
      )
      return res
    },
    onSuccess: (dataResending) => {
      queryClient.invalidateQueries({ queryKey: ['otp-record'] })
      toast.success(dataResending.message, { duration: 5000 })
      form.reset()
      start(60)
    },
  })

  const { mutate: mutateOtpVerif, isPending: isPendingOtpVerif } = useMutation({
    mutationFn: async (value: z.infer<typeof verifOtp>) => {
      return await fetchAPI(
        `${import.meta.env.VITE_API_BASE_URL}/auth/verif/otp`,
        {
          credentials: 'include',
          method: 'PATCH',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(value),
        },
      )
    },
    onSuccess: () => {
      toast.success('OTP verified successfully!')
      throw navigate({
        to: '/verification/password',
      })
    },
  })

  const isExpired = data?.data?.otpExpiresAt
    ? new Date(data.data.otpExpiresAt).getTime() < Date.now()
    : false

  const form = useAppForm({
    defaultValues: {
      otp_code: '',
    },
    validators: {
      onSubmit: verifOtp,
    },
    onSubmit: ({ value }) => {
      mutateOtpVerif(value)
    },
  })

  return (
    <div className="fixed top-1/2 left-1/2 -translate-y-1/2 -translate-x-1/2 w-xl bg-gray-50 shadow-2xl">
      <Card className="w-full max-w-xl shadow-lg">
        <CardHeader>
          <CardTitle className="text-2xl">Verify OTP</CardTitle>
          <CardDescription>
            Hello <b className="text-primary">{user?.username}</b>, please enter
            the OTP sent to your email, and please don't leave this page until
            you have verified your account.
          </CardDescription>
          <CardAction>
            <Button
              variant="link"
              type="button"
              disabled={countdown > 0 || isResending || isPendingOtpVerif}
              onClick={() => resendOtp()}
            >
              {isResending ? (
                <>
                  <span className="animate-spin mr-2">⏳</span>
                  Sending...
                </>
              ) : countdown > 0 ? (
                `Resend OTP in ${countdown}`
              ) : (
                'Resend OTP'
              )}
            </Button>
          </CardAction>
        </CardHeader>

        <form
          className="space-y-6"
          onSubmit={(e) => {
            e.preventDefault()
            form.handleSubmit()
          }}
        >
          <CardContent className="flex justify-center flex-col items-center gap-4">
            <Badge className="px-2 py-1">
              <Mail /> {user?.email}
            </Badge>
            <div className="max-w-xs w-full">
              <FieldGroup>
                <form.AppField name="otp_code">
                  {(field) => <field.Otp />}
                </form.AppField>
              </FieldGroup>
            </div>
          </CardContent>

          <CardFooter className="flex flex-col justify-start items-start">
            <ClientOnly
              fallback={
                <span className="text-gray-400">
                  Loading expiration status...
                </span>
              }
            >
              <ExpirationStatus expiresAt={data?.data?.otpExpiresAt} />
            </ClientOnly>

            <span className="text-sm text-muted-foreground">
              Please enter the OTP code sent to your email.
            </span>

            <Button
              type="submit"
              disabled={isPendingOtpVerif || isExpired}
              className="cursor-pointer"
            >
              {isPendingOtpVerif ? (
                <>
                  <span className="animate-spin mr-2">⏳</span>
                  Verifying...
                </>
              ) : (
                'Submit'
              )}
            </Button>
          </CardFooter>
        </form>
      </Card>
    </div>
  )
}
